// src/lib/seo.ts
export const defaultSEO = {
  title: 'MA Malnu Kananga - Membentuk Generasi Unggul yang Beriman dan Bertaqwa',
  description: 'Madrasah Aliyah Negeri Malnu Kananga menyelenggarakan pendidikan berkualitas yang mengintegrasikan nilai-nilai keislaman dengan kurikulum nasional.',
  keywords: 'MA Malnu Kananga, Madrasah Aliyah, Pendidikan Islam, PPDB, Sekolah Islam, Kananga',
  author: 'MA Malnu Kananga',
  themeColor: '#0A704D',
  language: 'id-ID',
  locale: 'id_ID',
  siteName: 'MA Malnu Kananga',
  type: 'website',
  image: '/images/og-image.jpg',
  imageAlt: 'Logo MA Malnu Kananga',
}

export const socialSEO = {
  twitter: {
    site: '@MALnuKananga',
    creator: '@MALnuKananga',
    cardType: 'summary_large_image',
  },
  facebook: {
    appId: 'XXXXXXXXXXXXXXX',
  },
}

// SEO configuration for different page types
export const pageSEO = {
  home: {
    title: 'MA Malnu Kananga - Membentuk Generasi Unggul yang Beriman dan Bertaqwa',
    description: 'Madrasah Aliyah Negeri Malnu Kananga menyelenggarakan pendidikan berkualitas yang mengintegrasikan nilai-nilai keislaman dengan kurikulum nasional.',
    image: '/images/og-home.jpg',
    imageAlt: 'Beranda MA Malnu Kananga',
    url: '/',
    priority: 1.0,
    changeFrequency: 'daily',
  },
  profil: {
    title: 'Profil Sekolah - MA Malnu Kananga',
    description: 'Informasi lengkap tentang MA Malnu Kananga, sejarah, visi misi, dan fasilitas sekolah.',
    image: '/images/og-profile.jpg',
    imageAlt: 'Profil MA Malnu Kananga',
    url: '/profil',
    priority: 0.8,
    changeFrequency: 'monthly',
  },
  berita: {
    title: 'Berita & Pengumuman - MA Malnu Kananga',
    description: 'Berita terkini dan pengumuman penting dari MA Malnu Kananga. Ikuti informasi kegiatan sekolah, prestasi siswa, dan program unggulan.',
    image: '/images/og-news.jpg',
    imageAlt: 'Berita MA Malnu Kananga',
    url: '/berita',
    priority: 0.9,
    changeFrequency: 'daily',
  },
  ppdb: {
    title: 'PPDB MA Malnu Kananga - Penerimaan Peserta Didik Baru',
    description: 'Informasi lengkap tentang Penerimaan Peserta Didik Baru (PPDB) MA Malnu Kananga. Syarat pendaftaran, jadwal, biaya, dan alur pendaftaran.',
    image: '/images/og-ppdb.jpg',
    imageAlt: 'PPDB MA Malnu Kananga',
    url: '/ppdb',
    priority: 0.9,
    changeFrequency: 'daily',
  },
  akademik: {
    title: 'Program Akademik - MA Malnu Kananga',
    description: 'Informasi tentang program akademik, kurikulum, dan kegiatan pembelajaran di MA Malnu Kananga.',
    image: '/images/og-academic.jpg',
    imageAlt: 'Program Akademik MA Malnu Kananga',
    url: '/akademik',
    priority: 0.8,
    changeFrequency: 'weekly',
  },
  kontak: {
    title: 'Kontak Kami - MA Malnu Kananga',
    description: 'Informasi kontak MA Malnu Kananga, alamat, nomor telepon, dan email resmi sekolah.',
    image: '/images/og-contact.jpg',
    imageAlt: 'Kontak MA Malnu Kananga',
    url: '/kontak',
    priority: 0.7,
    changeFrequency: 'monthly',
  },
  galeri: {
    title: 'Galeri Kegiatan - MA Malnu Kananga',
    description: 'Dokumentasi kegiatan sekolah, prestasi siswa, dan momen berharga di MA Malnu Kananga.',
    image: '/images/og-gallery.jpg',
    imageAlt: 'Galeri MA Malnu Kananga',
    url: '/galeri',
    priority: 0.7,
    changeFrequency: 'weekly',
  },
  pengumuman: {
    title: 'Pengumuman Terbaru - MA Malnu Kananga',
    description: 'Pengumuman penting dan terkini dari MA Malnu Kananga untuk siswa, orang tua, dan masyarakat.',
    image: '/images/og-announcement.jpg',
    imageAlt: 'Pengumuman MA Malnu Kananga',
    url: '/pengumuman',
    priority: 0.9,
    changeFrequency: 'daily',
  },
  prestasi: {
    title: 'Prestasi Sekolah - MA Malnu Kananga',
    description: 'Prestasi yang diraih oleh siswa dan sekolah MA Malnu Kananga dalam berbagai bidang.',
    image: '/images/og-achievement.jpg',
    imageAlt: 'Prestasi MA Malnu Kananga',
    url: '/prestasi',
    priority: 0.7,
    changeFrequency: 'weekly',
  },
  'guru-staf': {
    title: 'Guru dan Staf - MA Malnu Kananga',
    description: 'Kenali para guru dan staf pengajar profesional di MA Malnu Kananga yang berdedikasi tinggi.',
    image: '/images/og-teacher.jpg',
    imageAlt: 'Guru dan Staf MA Malnu Kananga',
    url: '/guru-staf',
    priority: 0.7,
    changeFrequency: 'monthly',
  },
}