# Issue Labels Configuration for website-ma-malnu
# This file defines the standard labels used in the repository

## Priority Labels
priority/critical:
  color: "b60205"
  description: "Critical priority - blocks core functionality or security"

priority/high:
  color: "d93f0b"
  description: "High priority - affects many users or important features"

priority/medium:
  color: "fbca04"
  description: "Medium priority - normal feature/bug work"

priority/low:
  color: "7057ff"
  description: "Low priority - minor improvements or nice-to-haves"

## Type Labels
bug:
  color: "d73a4a"
  description: "Something isn't working"

enhancement:
  color: "a2eeef"
  description: "New feature or improvement"

feature-request:
  color: "84b6eb"
  description: "Request for new functionality"

documentation:
  color: "0075ca"
  description: "Improvements or additions to documentation"

performance:
  color: "1d76db"
  description: "Performance issues or optimizations"

security:
  color: "ee0701"
  description: "Security vulnerabilities or concerns"

## Status Labels
status/triage:
  color: "ededed"
  description: "Needs triage and prioritization"

status/in-progress:
  color: "f9d0c4"
  description: "Currently being worked on"

status/review:
  color: "fef2c0"
  description: "Awaiting review or feedback"

status/done:
  color: "c2e0c6"
  description: "Completed and resolved"

status/blocked:
  color: "d4c5f9"
  description: "Blocked by dependencies or issues"

status/needs-info:
  color: "f6f8fa"
  description: "Needs more information from reporter"

## Component Labels
component/ppdb:
  color: "5319e7"
  description: "Related to PPDB registration system"

component/frontend:
  color: "0366d6"
  description: "Frontend components and UI"

component/backend:
  color: "1a202c"
  description: "Backend API and server logic"

component/database:
  color: "586069"
  description: "Database schema and queries"

component/deployment:
  color: "e99695"
  description: "Deployment and infrastructure"

component/seo:
  color: "c5def5"
  description: "SEO and metadata optimization"

component/accessibility:
  color: "006b75"
  description: "Accessibility and WCAG compliance"

## Size Labels
size/small:
  color: "c7def8"
  description: "Small task (1-3 hours)"

size/medium:
  color: "c2e0c6"
  description: "Medium task (3-8 hours)"

size/large:
  color: "fbca04"
  description: "Large task (8+ hours)"

## Special Labels
good first issue:
  color: "7057ff"
  description: "Good for newcomers"

help wanted:
  color: "008672"
  description: "Community help needed"

wontfix:
  color: "ffffff"
  description: "Will not be fixed or implemented"

duplicate:
  color: "cfd3d7"
  description: "Duplicate of another issue"

question:
  color: "d876e3"
  description: "Question or clarification needed"

## Educational Context Labels
context/student-facing:
  color: "b1e4b3"
  description: "Visible to students"

context/parent-facing:
  color: "ffdab9"
  description: "Visible to parents/guardians"

context/admin-facing:
  color: "e4b3ff"
  description: "For school administrators"

context/teacher-facing:
  color: "b3d9ff"
  description: "For teachers and staff"

## Automation Labels
automation:
  color: "f6f8fa"
  description: "Automatically generated by workflows"

stale:
  color: "f6f8fa"
  description: "No recent activity"

weekly-summary:
  color: "f6f8fa"
  description: "Weekly activity summary"