@echo off
REM Security Setup Test Script for Windows
REM This script tests all security workflows and configurations

echo 🔒 Testing Security Setup for sulhicmz/website-ma-malnu
echo ==================================================

REM Check if GitHub CLI is installed
echo 🔍 Checking GitHub CLI...
gh --version >nul 2>&1
if %errorlevel% neq 0 (
    echo ❌ GitHub CLI is not installed
    echo Please install GitHub CLI: https://cli.github.com/
    pause
    exit /b 1
) else (
    echo ✅ GitHub CLI is installed
    gh --version
)

REM Test repository access
echo.
echo 🔍 Testing Repository Access...
gh repo view sulhicmz/website-ma-malnu >nul 2>&1
if %errorlevel% neq 0 (
    echo ❌ Cannot access repository
    echo Please check your GitHub authentication
    pause
    exit /b 1
) else (
    echo ✅ Repository access confirmed
)

REM Test security workflows
echo.
echo 🔍 Testing Security Workflows...
if exist ".github\workflows\security.yml" (
    echo ✅ security.yml exists
) else (
    echo ❌ security.yml not found
)

if exist ".github\workflows\advanced-security.yml" (
    echo ✅ advanced-security.yml exists
) else (
    echo ❌ advanced-security.yml not found
)

if exist ".github\workflows\security-monitoring.yml" (
    echo ✅ security-monitoring.yml exists
) else (
    echo ❌ security-monitoring.yml not found
)

if exist ".github\workflows\static-analysis.yml" (
    echo ✅ static-analysis.yml exists
) else (
    echo ❌ static-analysis.yml not found
)

if exist ".github\workflows\emergency-security.yml" (
    echo ✅ emergency-security.yml exists
) else (
    echo ❌ emergency-security.yml not found
)

REM Test Dependabot configuration
echo.
echo 🔍 Testing Dependabot Configuration...
if exist ".github\dependabot.yml" (
    echo ✅ dependabot.yml exists
) else (
    echo ❌ dependabot.yml not found
)

REM Test CodeQL configuration
echo.
echo 🔍 Testing CodeQL Configuration...
if exist ".github\codeql\codeql-config.yml" (
    echo ✅ CodeQL configuration exists
) else (
    echo ❌ CodeQL configuration not found
)

REM Test security policy
echo.
echo 🔍 Testing Security Policy...
if exist "SECURITY.md" (
    echo ✅ SECURITY.md exists
) else (
    echo ❌ SECURITY.md not found
)

REM Test package.json
echo.
echo 🔍 Testing Package Security...
if exist "package.json" (
    echo ✅ package.json exists
    
    echo Running npm audit...
    npm audit --audit-level=moderate
    if %errorlevel% equ 0 (
        echo ✅ No moderate or high vulnerabilities found
    ) else (
        echo ❌ Vulnerabilities found - check npm audit output
    )
) else (
    echo ❌ package.json not found
)

REM Test environment files
echo.
echo 🔍 Testing Environment Files...
if exist ".env.example" (
    echo ✅ .env.example exists
) else (
    echo ❌ .env.example not found
)

if exist ".env.local.example" (
    echo ✅ .env.local.example exists
) else (
    echo ❌ .env.local.example not found
)

REM Generate report
echo.
echo 🔍 Generating Security Test Report...
set report_file=security-test-report-%date:~-4,4%%date:~-10,2%%date:~-7,2%-%time:~0,2%%time:~3,2%%time:~6,2%.md
set report_file=%report_file: =0%

# Security Setup Test Report > %report_file%
echo **Repository**: sulhicmz/website-ma-malnu >> %report_file%
echo **Date**: %date% %time% >> %report_file%
echo **Tested by**: >> %report_file%
gh api user --jq '.login' >> %report_file%
echo. >> %report_file%

echo ## Test Summary >> %report_file%
echo This report contains the results of the security setup test. >> %report_file%
echo. >> %report_file%

echo ## Tests Performed >> %report_file%
echo 1. ✅ GitHub CLI access >> %report_file%
echo 2. ✅ Repository access >> %report_file%
echo 3. ✅ Security workflows validation >> %report_file%
echo 4. ✅ Dependabot configuration >> %report_file%
echo 5. ✅ CodeQL configuration >> %report_file%
echo 6. ✅ Security policy >> %report_file%
echo 7. ✅ Package security >> %report_file%
echo 8. ✅ Environment files >> %report_file%
echo. >> %report_file%

echo ## Next Steps >> %report_file%
echo 1. Review any failed tests >> %report_file%
echo 2. Configure missing secrets in GitHub repository settings >> %report_file%
echo 3. Enable Advanced Security features in repository settings >> %report_file%
echo 4. Monitor workflow runs in Actions tab >> %report_file%
echo 5. Set up security notifications >> %report_file%
echo. >> %report_file%

echo ---
echo *Generated by security test script* >> %report_file%

echo ✅ Security test report generated: %report_file%

echo.
echo ==================================================
echo 🎉 Security setup test completed!
echo 📊 Check the generated report for details
echo 🔧 Review any failed tests and follow the setup guide
echo ==================================================

pause