import { defineField, defineType } from 'sanity'

export default defineType({
  name: 'ppdbSubmission',
  title: 'PPDB Submission',
  type: 'document',
  groups: [
    { name: 'siswa', title: 'Data Siswa' },
    { name: 'orangTua', title: 'Data Orang Tua' },
    { name: 'wali', title: 'Data Wali' },
    { name: 'jurusan', title: 'Pilihan Jurusan' },
    { name: 'dokumen', title: 'Dokumen' },
  ],
  fields: [
    defineField({
      name: 'submittedAt',
      title: 'Tanggal Submit',
      type: 'datetime',
      readOnly: true,
      group: 'siswa',
    }),
    defineField({
      name: 'status',
      title: 'Status Verifikasi',
      type: 'string',
      options: {
        list: [
          { title: 'Baru', value: 'baru' },
          { title: 'Diverifikasi', value: 'diverifikasi' },
          { title: 'Ditolak', value: 'ditolak' },
        ],
        layout: 'radio',
      },
      initialValue: 'baru',
      group: 'siswa',
    }),
    defineField({
      name: 'namaLengkap',
      title: 'Nama Lengkap',
      type: 'string',
      group: 'siswa',
    }),
    defineField({
      name: 'jenisKelamin',
      title: 'Jenis Kelamin',
      type: 'string',
      options: {
        list: [
          { title: 'Laki-laki', value: 'laki-laki' },
          { title: 'Perempuan', value: 'perempuan' },
        ],
      },
      group: 'siswa',
    }),
    defineField({
      name: 'tempatLahir',
      title: 'Tempat Lahir',
      type: 'string',
      group: 'siswa',
    }),
    defineField({
      name: 'tanggalLahir',
      title: 'Tanggal Lahir',
      type: 'date',
      group: 'siswa',
    }),
    defineField({
      name: 'nik',
      title: 'NIK',
      type: 'string',
      group: 'siswa',
    }),
    defineField({
      name: 'nisn',
      title: 'NISN',
      type: 'string',
      group: 'siswa',
    }),
    defineField({
      name: 'alamat',
      title: 'Alamat',
      type: 'text',
      rows: 3,
      group: 'siswa',
    }),
    defineField({
      name: 'kecamatan',
      title: 'Kecamatan',
      type: 'string',
      group: 'siswa',
    }),
    defineField({
      name: 'kabupaten',
      title: 'Kabupaten/Kota',
      type: 'string',
      group: 'siswa',
    }),
    defineField({
      name: 'provinsi',
      title: 'Provinsi',
      type: 'string',
      group: 'siswa',
    }),
    defineField({
      name: 'kodePos',
      title: 'Kode Pos',
      type: 'string',
      group: 'siswa',
    }),
    defineField({
      name: 'noTelepon',
      title: 'Nomor Telepon',
      type: 'string',
      group: 'siswa',
    }),
    defineField({
      name: 'email',
      title: 'Email',
      type: 'string',
      group: 'siswa',
    }),
    defineField({
      name: 'persetujuan',
      title: 'Persetujuan Syarat & Ketentuan',
      type: 'boolean',
      group: 'siswa',
    }),
    defineField({
      name: 'asalSekolah',
      title: 'Asal Sekolah',
      type: 'string',
      group: 'siswa',
    }),
    defineField({
      name: 'alamatSekolah',
      title: 'Alamat Sekolah',
      type: 'text',
      rows: 3,
      group: 'siswa',
    }),
    defineField({
      name: 'npsnSekolah',
      title: 'NPSN Sekolah',
      type: 'string',
      group: 'siswa',
    }),
    defineField({
      name: 'tahunLulus',
      title: 'Tahun Lulus',
      type: 'string',
      group: 'siswa',
    }),
    defineField({
      name: 'nilaiUN',
      title: 'Nilai Ujian Nasional',
      type: 'object',
      fields: [
        defineField({ name: 'indonesia', title: 'Bahasa Indonesia', type: 'number' }),
        defineField({ name: 'inggris', title: 'Bahasa Inggris', type: 'number' }),
        defineField({ name: 'matematika', title: 'Matematika', type: 'number' }),
        defineField({ name: 'ipa', title: 'IPA', type: 'number' }),
      ],
      group: 'siswa',
    }),
    defineField({
      name: 'namaAyah',
      title: 'Nama Ayah',
      type: 'string',
      group: 'orangTua',
    }),
    defineField({
      name: 'nikAyah',
      title: 'NIK Ayah',
      type: 'string',
      group: 'orangTua',
    }),
    defineField({
      name: 'pendidikanAyah',
      title: 'Pendidikan Ayah',
      type: 'string',
      group: 'orangTua',
    }),
    defineField({
      name: 'pekerjaanAyah',
      title: 'Pekerjaan Ayah',
      type: 'string',
      group: 'orangTua',
    }),
    defineField({
      name: 'penghasilanAyah',
      title: 'Penghasilan Ayah',
      type: 'string',
      group: 'orangTua',
    }),
    defineField({
      name: 'noTeleponAyah',
      title: 'Nomor Telepon Ayah',
      type: 'string',
      group: 'orangTua',
    }),
    defineField({
      name: 'namaIbu',
      title: 'Nama Ibu',
      type: 'string',
      group: 'orangTua',
    }),
    defineField({
      name: 'nikIbu',
      title: 'NIK Ibu',
      type: 'string',
      group: 'orangTua',
    }),
    defineField({
      name: 'pendidikanIbu',
      title: 'Pendidikan Ibu',
      type: 'string',
      group: 'orangTua',
    }),
    defineField({
      name: 'pekerjaanIbu',
      title: 'Pekerjaan Ibu',
      type: 'string',
      group: 'orangTua',
    }),
    defineField({
      name: 'penghasilanIbu',
      title: 'Penghasilan Ibu',
      type: 'string',
      group: 'orangTua',
    }),
    defineField({
      name: 'noTeleponIbu',
      title: 'Nomor Telepon Ibu',
      type: 'string',
      group: 'orangTua',
    }),
    defineField({
      name: 'namaWali',
      title: 'Nama Wali',
      type: 'string',
      group: 'wali',
    }),
    defineField({
      name: 'hubunganWali',
      title: 'Hubungan Wali',
      type: 'string',
      group: 'wali',
    }),
    defineField({
      name: 'nikWali',
      title: 'NIK Wali',
      type: 'string',
      group: 'wali',
    }),
    defineField({
      name: 'pendidikanWali',
      title: 'Pendidikan Wali',
      type: 'string',
      group: 'wali',
    }),
    defineField({
      name: 'pekerjaanWali',
      title: 'Pekerjaan Wali',
      type: 'string',
      group: 'wali',
    }),
    defineField({
      name: 'penghasilanWali',
      title: 'Penghasilan Wali',
      type: 'string',
      group: 'wali',
    }),
    defineField({
      name: 'noTeleponWali',
      title: 'Nomor Telepon Wali',
      type: 'string',
      group: 'wali',
    }),
    defineField({
      name: 'jurusanPilihan',
      title: 'Jurusan Pilihan',
      type: 'string',
      options: {
        list: [
          { title: 'IPA', value: 'ipa' },
          { title: 'IPS', value: 'ips' },
        ],
      },
      group: 'jurusan',
    }),
    defineField({
      name: 'alasanPilihan',
      title: 'Alasan Memilih Jurusan',
      type: 'text',
      rows: 4,
      group: 'jurusan',
    }),
    defineField({
      name: 'dokumen',
      title: 'Dokumen Unggahan',
      type: 'array',
      of: [
        defineField({
          name: 'file',
          title: 'File',
          type: 'file',
          fields: [
            defineField({
              name: 'jenis',
              title: 'Jenis Dokumen',
              type: 'string',
              options: {
                list: [
                  { title: 'Pas Foto', value: 'foto' },
                  { title: 'Akta Kelahiran', value: 'aktaKelahiran' },
                  { title: 'Kartu Keluarga', value: 'kartuKeluarga' },
                  { title: 'Ijazah', value: 'ijazah' },
                  { title: 'SKHUN', value: 'skhun' },
                  { title: 'Rapor', value: 'rapor' },
                ],
              },
            }),
            defineField({
              name: 'fileName',
              title: 'Nama File',
              type: 'string',
              readOnly: true,
            }),
          ],
        }),
      ],
      group: 'dokumen',
    }),
  ],
})
